### ISSUE TITLE
updates for ui-kit to use it as submodule

### ISSUE THREAD

**Issue by vladyslav2** [webdevelop-pro/ui-kit#9]
@nelyaklyusa 

1. Поперше, давай заберемо security [PRs](https://github.com/webdevelop-pro/ui-kit/pulls) та загалом оновимо залежності (якщо це реально і не сильно довго)
2. в коді не використовувати сімвол `@/` для import тк він кофліктує з основнім проектом.
3. в [vite.config.ts](https://github.com/webdevelop-pro/ui-kit/blob/dev/vite.config.ts#L12) зминити `@` на, наприклад UIKit 
4. в основному проекту використовувати зміну UIKit з повним шляхом до папці src в ui-kit, тобто `'UIKit': path.resolve(__dirname, './ui-kit/src'),`
5. для пери `ui-kit` обов'язково робити релизи та теги. submodule підключати як определенний тег, не використовувати master branch у submodulі
6. submodule підключати через git протокол, тобто  `git submodule add -b <tab> git@github.com:webdevelop-pro/ui-kit.git ui-kit`

**Comment by imaksimova** [comment]
as discussed with @nelyaklyusa it still has some work to finish later. But it is deprioritised now, see in https://github.com/webdevelop-pro/invest.webdevelop.pro/issues/613
@nelyaklyusa I'll put it into blocked column for now.

**Comment by imaksimova** [comment]
@vladyslav2 I have no permissions to assign pre-launch milestone for this repo's ticket.
